Examples and README
LCMApps/drover pull request #1
Opened 2019-07-12 07:29 UTC by JanGolle

2019-07-15 15:00 UTC, WoZ requested changes
Great job!

I have a few comments to improve docs.
1. Suppose it's a good idea to include info about the difference with PM2: MIT license instead of GPL (check the license plz), more flexible programmatic control. As I see, PM2's programmatic control is just API to pm2 process and you may use only a given subset of strategies, like restart after N queries. With drover you may add any logic you want. PM2 uses "let it fail" concept while drover shares idea of control. E.g. difference about normal and abnormal stop. Feature to run different groups and manage them.
2. It's better to add a section with the code right after install block. Just like starting a very simple app. The idea to exploit user's attention (max 10-15 sec) to understand what we are talking about. User must come around that it's easy to use.
3. Maybe we need to add a separate section with a description of differences between PM2 and drover.

2019-07-15 15:00 UTC, WoZ commented on README.md
> +        case ExitReasons.ExternalSignal:
I hadn't found any mention that reason is an instance of `ExitReason.*` class. Up for me it's better to use `if (reason instanceof ExitReasons.ExternalSignal) {...} elseif () {...}`. It's more obvious than having `reason.constructor` that may be a regular constant field with constants like `ExitReasons.ExternalSignal`.

2019-07-15 15:00 UTC, WoZ commented on README.md
> +            await quit(code, signal, true);
What is `quit`? If you write code with that below just write a comment in this line that `quit` will be described later.

2019-07-16 10:37 UTC, JanGolle commented on README.md
> +        case ExitReasons.ExternalSignal:
Agree, done!

2019-07-16 10:37 UTC, JanGolle commented on README.md
> +            await quit(code, signal, true);
Yes for sure, missed it

2019-07-17 10:15 UTC, WoZ approved these changes

2019-07-17 10:15 UTC, merged